#!/bin/bash
# this script was generated by /home/zingile/git/qatizen/node_modules/libqa/executors/PACKAGE.js

set -e
resdir=/tmp
resfile=$resdir/testkit.result.xml

echo '## execution script: preparing environment'
rm -rf $resdir/*.result.xml

timeout 10800 testkit-lite -f /usr/share/tests/ivi/ivi-sanity-suite/testkit.xml --comm localhost -o $resfile

echo '## execution script: finished'
